#!/usr/bin/env python3
"""Discrete Franck-Condon lines -- figure script generated by fcenvelope.

    python <this file> [DATA.json]

Everything that decides how this figure looks is in this file, and the data is
read from the result JSON at run time. Recompute with different conditions and
run this script again to get the same figure for the new numbers.

This file is yours. fcenvelope never reads it back; edit anything below.
"""

from __future__ import annotations

import base64
import io
import sys
import json
from pathlib import Path

import matplotlib.pyplot as plt

# --- generated header (fcenvelope) ---------------------------------------
DATA = Path(__file__).parent / "lines.json"
OUTPUT = Path(__file__).parent / "fcenvelope-lines.png"
KIND = "fcenvelope.fc_lines"
SCHEMA_VERSION = 2
# --- end generated header ------------------------------------------------

# 出力先。SHOW は None なら端末のときだけ、True / False で固定できる。
SAVE = True
SHOW = None
SHOW_WIDTH = 0.9     # 端末の幅に対する図の幅の割合
SHOW_DPI = 110       # 端末が画素数を返さないときの解像度。ファイルの DPI とは別
IMAGE_PREFIX = "fcenvelope-"   # 引数でほかの結果を指したときの画像名の頭

# 図の設定。ここから下はすべて手で変えてよい。
FIGSIZE = (7.0, 4.2)
DPI = 150
TITLE = None
LABEL = None
COLOR = "C0"
LINEWIDTH = 1.2
XLIM = None          # None なら線の立つ範囲いっぱい。(-3000.0, 500.0) と書ける
YLIM = None
GUIDE = {"color": "0.7", "linewidth": 0.8, "zorder": 0}

# 横軸の単位。計算は常に cm^-1 で行われているので、ここは表示の掛け算だけ。
# 縦軸の重みは無次元なので、こちらは換算しない。
#   eV にするなら  X_UNIT, X_SCALE = "eV", 1.0 / 8065.543937
X_UNIT = "cm$^{-1}$"
X_SCALE = 1.0


def beside(path: Path | str) -> Path:
    """スクリプトの中に書いたファイル名を、このスクリプトの隣として読む。

    生成ヘッダの位置がこのファイルからの相対で解決される（ADR-0059）のに合わせる。
    2 本目を足すときに書くファイル名も同じ基準になるので、どこから起動しても同じ図が
    出る。コマンドラインの引数はシェルの都合でカレントディレクトリ基準なので、`main`
    が先に絶対パスへ直してから渡す（ADR-0067）。
    """
    path = Path(path)
    return path if path.is_absolute() else Path(__file__).parent / path


def load(path: Path | str, kind: str) -> dict:
    """結果 JSON を読む。種類と版が合わなければ読める文言で止まる。"""
    path = beside(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("kind") != kind or data.get("schema_version") != SCHEMA_VERSION:
        raise SystemExit(
            f"{path}: expected {kind} (schema {SCHEMA_VERSION}), got "
            f"{data.get('kind')!r} (schema {data.get('schema_version')!r})"
        )
    return data


def terminal_pixel_width() -> int | None:
    """端末の窓の画素幅。返さない端末もあるので、その場合は None。"""
    try:
        import fcntl
        import struct
        import termios

        packed = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, b"\0" * 8)
    except (ImportError, OSError):
        return None
    return struct.unpack("HHHH", packed)[2] or None      # rows, cols, xpixel, ypixel


def show(fig) -> None:
    """kitty graphics protocol で端末に直接出す。別の端末なら、ここを書き替える。"""
    pixels = terminal_pixel_width()
    dpi = pixels * SHOW_WIDTH / FIGSIZE[0] if pixels else SHOW_DPI

    buffer = io.BytesIO()
    fig.savefig(buffer, format="png", dpi=dpi)
    payload = base64.standard_b64encode(buffer.getvalue())

    out, first = sys.stdout.buffer, True
    while payload:                       # 制御データは先頭のみ、以降は m= だけ
        head, payload = payload[:4096], payload[4096:]
        control = "a=T,f=100,q=2," if first else ""
        out.write(
            b"\033_G" + f"{control}m={int(bool(payload))}".encode()
            + b";" + head + b"\033\\"
        )
        first = False
    out.write(b"\n")
    out.flush()


def image_for(source: Path) -> Path:
    """図の書き出し先。引数でほかの結果を指したときは、その名前に追従する。

    既定のデータを描くなら OUTPUT で、手で書き替えたものがそのまま効く。別の結果を
    指したなら、その結果の隣に `fcenvelope-<結果の名前>.png` を置く。条件を振った
    結果を同じ設定で描いて見比べるときに、前の図を潰さないためである（ADR-0067）。
    """
    if source.resolve() == DATA.resolve():
        return OUTPUT
    return source.with_name(f"{IMAGE_PREFIX}{source.stem}.png")


def draw(ax, data: dict, *, label: str | None = LABEL, color: str = COLOR) -> None:
    """離散 FC 因子を底辺 0 の棒として描く。図の中身はここだけ。"""
    energy = [line["energy"] * X_SCALE for line in data["lines"]]
    weight = [line["weight"] for line in data["lines"]]

    ax.vlines(energy, 0.0, weight, colors=color, linewidth=LINEWIDTH, label=label)
    ax.axvline(0.0, **GUIDE)             # E = 0 は ZPL
    ax.axhline(0.0, **GUIDE)
    ax.set_xlabel(f"$E$ / {X_UNIT}")
    ax.set_ylabel("weight")              # 熱占有を含む確率質量。総和が 1


def main() -> None:
    # 引数はシェルの都合でカレントディレクトリ基準。ここで絶対パスに直しておくと、
    # 以降はスクリプトの隣を指す DATA と同じに扱える（ADR-0067）。
    source = Path(sys.argv[1]).absolute() if len(sys.argv) > 1 else DATA
    data = load(source, KIND)
    output = image_for(source)

    fig, ax = plt.subplots(figsize=FIGSIZE, layout="constrained")
    draw(ax, data)

    # 2 本目を重ねるとき（温度を振った比較など）:
    # draw(ax, load("lines_100K.json", KIND), label="100 K", color="C3")

    if TITLE is not None:
        ax.set_title(TITLE)
    if XLIM is not None:
        ax.set_xlim(*XLIM)
    if YLIM is not None:
        ax.set_ylim(*YLIM)
    if ax.get_legend_handles_labels()[1]:
        ax.legend()

    if SAVE:
        # 見た目には出ない覚え書きを PNG のテキストチャンクに入れておく。
        fig.savefig(output, dpi=DPI, metadata={
            "Software": f"fcenvelope {data['fcenvelope_version']}",
            "Source": f"{source.name} ({data['created_at']})",
            "Description": f"T = {data['input']['temperature']:g} K, "
                           f"{len(data['lines'])} lines",
        })
        print(f"wrote {output}")
    if SHOW if SHOW is not None else sys.stdout.isatty():
        show(fig)


if __name__ == "__main__":
    main()
