#!/usr/bin/env python3
"""Discrete Franck-Condon lines -- figure script generated by fcenvelope.

    python <this file> [DATA.json]

Everything that decides how this figure looks is in this file, and the data is
read from the result JSON at run time. Recompute with different conditions and
run this script again to get the same figure for the new numbers.

This file is yours. fcenvelope never reads it back; edit anything below.
"""

from __future__ import annotations

import base64
import io
import math
import os
import sys
import json
from pathlib import Path

import matplotlib.pyplot as plt

# --- generated header (fcenvelope) ---------------------------------------
DATA = Path(__file__).parent / "lines.json"
OUTPUT = Path(__file__).parent / "fcenvelope-lines.png"
KIND = "fcenvelope.fc_lines"
SCHEMA_VERSION = 2
# --- end generated header ------------------------------------------------

# 出力先。SHOW は None なら端末のときだけ、True / False で固定できる。
SAVE = True
SHOW = None
SHOW_SIZE = 0.5      # 端末の窓の幅・高さに対する図の大きさの上限の割合
SHOW_DPI = 110       # 端末が画素数を返さないときの解像度。ファイルの DPI とは別
IMAGE_PREFIX = "fcenvelope-"   # 引数でほかの結果を指したときの画像名の頭

# 図の設定。ここから下はすべて手で変えてよい。
FIGSIZE = (7.0, 4.2)
DPI = 150
TITLE = None
LABEL = None
COLOR = "C0"
LINEWIDTH = 1.2
XLIM = None          # None なら線の立つ範囲いっぱい。(-3000.0, 500.0) と書ける
YLIM = None
GUIDE = {"color": "0.7", "linewidth": 0.8, "zorder": 0}

# 横軸の単位。計算は常に cm^-1 で行われているので、ここは表示の掛け算だけ。
# 縦軸の重みは無次元なので、こちらは換算しない。
#   eV にするなら  X_UNIT, X_SCALE = "eV", 1.0 / 8065.543937
X_UNIT = "cm$^{-1}$"
X_SCALE = 1.0


def beside(path: Path | str) -> Path:
    """スクリプトの中に書いたファイル名を、このスクリプトの隣として読む。

    生成ヘッダの位置がこのファイルからの相対で解決される（ADR-0059）のに合わせる。
    2 本目を足すときに書くファイル名も同じ基準になるので、どこから起動しても同じ図が
    出る。コマンドラインの引数はシェルの都合でカレントディレクトリ基準なので、`main`
    が先に絶対パスへ直してから渡す（ADR-0067）。
    """
    path = Path(path)
    return path if path.is_absolute() else Path(__file__).parent / path


def load(path: Path | str, kind: str) -> dict:
    """結果 JSON を読む。種類と版が合わなければ読める文言で止まる。"""
    path = beside(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("kind") != kind or data.get("schema_version") != SCHEMA_VERSION:
        raise SystemExit(
            f"{path}: expected {kind} (schema {SCHEMA_VERSION}), got "
            f"{data.get('kind')!r} (schema {data.get('schema_version')!r})"
        )
    return data


def column(table: dict, name: str) -> list:
    """結果ファイルの表から 1 列を取り出す。

    表は `columns`（列名か `[列名, "単位"]`）と `rows`（行ごとの値の並び）で書かれている。
    入力ファイルで CSV の列を書くのと同じ形である。単位は計算と同じ cm^-1 系で固定。
    """
    names = [spec if isinstance(spec, str) else spec[0] for spec in table["columns"]]
    index = names.index(name)
    return [row[index] for row in table["rows"]]


def terminal_size() -> tuple[int, int, int, int]:
    """端末の窓の (行数, 桁数, 画素幅, 画素高さ)。分からない値は 0。"""
    try:
        import fcntl
        import struct
        import termios

        packed = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, b"\0" * 8)
    except (ImportError, OSError):
        return 0, 0, 0, 0
    return struct.unpack("HHHH", packed)


def in_tmux() -> bool:
    """tmux の中か。tmux は画像の列を素通しさせないので、包んで渡す必要がある。"""
    return bool(os.environ.get("TMUX"))


def passthrough(sequence: bytes) -> bytes:
    """tmux の中なら、外の端末へ届くように包む。tmux 側で allow-passthrough が要る。"""
    if not in_tmux():
        return sequence
    return b"\033Ptmux;" + sequence.replace(b"\033", b"\033\033") + b"\033\\"


def show(fig) -> None:
    """kitty graphics protocol で端末に直接出す。別の端末なら、ここを書き替える。

    図は窓の幅と高さの SHOW_SIZE 倍に収まる大きさで描く。窓の画素数が分かれば解像度を
    そこから逆算して端末に縮小させず、分からなければ SHOW_DPI で描いて行数だけ指定する。
    tmux の中では画像を文字（unicode placeholder）として置き、スクロールやペインの
    切り替えに追従させる。
    """
    rows, columns, xpixel, ypixel = terminal_size()
    width, height = fig.get_size_inches()
    if rows and columns and xpixel and ypixel:
        dpi = SHOW_SIZE * min(xpixel / width, ypixel / height)
        lines = math.ceil(height * dpi / (ypixel / rows))
        cells = math.ceil(width * dpi / (xpixel / columns))
        placement = ""
    else:
        dpi = SHOW_DPI
        lines = max(1, round(rows * SHOW_SIZE)) if rows else 1
        cells = max(1, round(lines * width / height * 2))   # 文字の縦横比を 2:1 と見る
        placement = f"r={lines}," if rows else ""

    buffer = io.BytesIO()
    fig.savefig(buffer, format="png", dpi=dpi)
    if in_tmux():
        lines = min(lines, len(PLACEHOLDER_DIACRITICS))
        image_id, low = placeholder_id()
        placement = f"U=1,i={image_id},c={cells},r={lines},"
    transmit(buffer.getvalue(), placement)
    if in_tmux():
        sys.stdout.buffer.write(placeholders(image_id, low, cells, lines))
    else:
        sys.stdout.buffer.write(b"\n")
    sys.stdout.buffer.flush()


def transmit(png: bytes, placement: str) -> None:
    """PNG を 4096 バイトずつに分けて送る。制御データは先頭のみ、以降は m= だけ。"""
    payload = base64.standard_b64encode(png)
    out, first = sys.stdout.buffer, True
    while payload:
        head, payload = payload[:4096], payload[4096:]
        control = f"a=T,f=100,q=2,{placement}" if first else ""
        out.write(passthrough(
            b"\033_G" + f"{control}m={int(bool(payload))}".encode()
            + b";" + head + b"\033\\"
        ))
        first = False


PLACEHOLDER = "\U0010EEEE"
PLACEHOLDER_DIACRITICS = [chr(int(code, 16)) for code in (
    "0305 030D 030E 0310 0312 033D 033E 033F 0346 034A 034B 034C "
    "0350 0351 0352 0357 035B 0363 0364 0365 0366 0367 0368 0369 "
    "036A 036B 036C 036D 036E 036F 0483 0484 0485 0486 0487 0592 "
    "0593 0594 0595 0597 0598 0599 059C 059D 059E 059F 05A0 05A1 "
    "05A8 05A9 05AB 05AC 05AF 05C4 0610 0611 0612 0613 0614 0615 "
    "0616 0617 0657 0658 0659 065A 065B 065D 065E 06D6 06D7 06D8 "
    "06D9 06DA 06DB 06DC 06DF 06E0 06E1 06E2 06E4 06E7 06E8 06EB "
    "06EC 0730 0732 0733 0735 0736 073A 073D 073F 0740 0741 0743 "
    "0745 0747 0749 074A 07EB 07EC 07ED 07EE 07EF 07F0 07F1 07F3 "
    "0816 0817 0818 0819 081B 081C 081D 081E 081F 0820 0821 0822 "
    "0823 0825 0826 0827 0829 082A 082B 082C 082D 0951 0953 0954 "
    "0F82 0F83 0F86 0F87 135D 135E 135F 17DD 193A 1A17 1A75 1A76 "
    "1A77 1A78 1A79 1A7A 1A7B 1A7C 1B6B 1B6D 1B6E 1B6F 1B70 1B71 "
    "1B72 1B73 1CD0 1CD1 1CD2 1CDA 1CDB 1CE0 1DC0 1DC1 1DC3 1DC4 "
    "1DC5 1DC6 1DC7 1DC8 1DC9 1DCB 1DCC 1DD1 1DD2 1DD3 1DD4 1DD5 "
    "1DD6 1DD7 1DD8 1DD9 1DDA 1DDB 1DDC 1DDD 1DDE 1DDF 1DE0 1DE1 "
    "1DE2 1DE3 1DE4 1DE5 1DE6 1DFE 20D0 20D1 20D4 20D5 20D6 20D7 "
    "20DB 20DC 20E1 20E7 20E9 20F0 2CEF 2CF0 2CF1 2DE0 2DE1 2DE2 "
    "2DE3 2DE4 2DE5 2DE6 2DE7 2DE8 2DE9 2DEA 2DEB 2DEC 2DED 2DEE "
    "2DEF 2DF0 2DF1 2DF2 2DF3 2DF4 2DF5 2DF6 2DF7 2DF8 2DF9 2DFA "
    "2DFB 2DFC 2DFD 2DFE 2DFF A66F A67C A67D A6F0 A6F1 A8E0 A8E1 "
    "A8E2 A8E3 A8E4 A8E5 A8E6 A8E7 A8E8 A8E9 A8EA A8EB A8EC A8ED "
    "A8EE A8EF A8F0 A8F1 AAB0 AAB2 AAB3 AAB7 AAB8 AABE AABF AAC1 "
    "FE20 FE21 FE22 FE23 FE24 FE25 FE26 10A0F 10A38 1D185 1D186 1D187 "
    "1D188 1D189 1D1AA 1D1AB 1D1AC 1D1AD 1D242 1D243 1D244"
).split()]
"""行・桁の番号を表す結合文字（kitty の rowcolumn-diacritics.txt の順）。"""


def placeholder_id() -> tuple[int, int]:
    """画像の番号と、その下位 1 バイト。前に出した画像と重ならないよう乱数で選ぶ。

    下位 1 バイトは 256 色の文字色で、上位 1 バイトは 3 つ目の結合文字で表す。
    """
    high, low = (1 + byte % 255 for byte in os.urandom(2))
    return high << 24 | low, low


def placeholders(image_id: int, low: int, cells: int, lines: int) -> bytes:
    """画像を置く文字の格子。各行の先頭にだけ行・桁・番号の上位を付け、残りは端末が補う。"""
    high = PLACEHOLDER_DIACRITICS[image_id >> 24]
    text = "".join(
        f"\033[38;5;{low}m" + PLACEHOLDER + PLACEHOLDER_DIACRITICS[line]
        + PLACEHOLDER_DIACRITICS[0] + high + PLACEHOLDER * (cells - 1) + "\033[39m\n"
        for line in range(lines)
    )
    return text.encode("utf-8")


def image_for(source: Path) -> Path:
    """図の書き出し先。引数でほかの結果を指したときは、その名前に追従する。

    既定のデータを描くなら OUTPUT で、手で書き替えたものがそのまま効く。別の結果を
    指したなら、その結果の隣に `fcenvelope-<結果の名前>.png` を置く。条件を振った
    結果を同じ設定で描いて見比べるときに、前の図を潰さないためである（ADR-0067）。
    """
    if source.resolve() == DATA.resolve():
        return OUTPUT
    return source.with_name(f"{IMAGE_PREFIX}{source.stem}.png")


def draw(ax, data: dict, *, label: str | None = LABEL, color: str = COLOR) -> None:
    """離散 FC 因子を底辺 0 の棒として描く。図の中身はここだけ。"""
    energy = [e * X_SCALE for e in column(data["lines"], "energy")]
    weight = column(data["lines"], "weight")

    ax.vlines(energy, 0.0, weight, colors=color, linewidth=LINEWIDTH, label=label)
    ax.axvline(0.0, **GUIDE)             # E = 0 は ZPL
    ax.axhline(0.0, **GUIDE)
    ax.set_xlabel(f"$E$ / {X_UNIT}")
    ax.set_ylabel("weight")              # 熱占有を含む確率質量。総和が 1


def main() -> None:
    # 引数はシェルの都合でカレントディレクトリ基準。ここで絶対パスに直しておくと、
    # 以降はスクリプトの隣を指す DATA と同じに扱える（ADR-0067）。
    source = Path(sys.argv[1]).absolute() if len(sys.argv) > 1 else DATA
    data = load(source, KIND)
    output = image_for(source)

    fig, ax = plt.subplots(figsize=FIGSIZE, layout="constrained")
    draw(ax, data)

    # 2 本目を重ねるとき（温度を振った比較など）:
    # draw(ax, load("lines_100K.json", KIND), label="100 K", color="C3")

    if TITLE is not None:
        ax.set_title(TITLE)
    if XLIM is not None:
        ax.set_xlim(*XLIM)
    if YLIM is not None:
        ax.set_ylim(*YLIM)
    if ax.get_legend_handles_labels()[1]:
        ax.legend()

    if SAVE:
        # 見た目には出ない覚え書きを PNG のテキストチャンクに入れておく。
        fig.savefig(output, dpi=DPI, metadata={
            "Software": f"fcenvelope {data['fcenvelope_version']}",
            "Source": f"{source.name} ({data['created_at']})",
            "Description": f"T = {data['conditions']['temperature']:g} K, "
                           f"{len(data['lines']['rows'])} lines",
        })
        print(f"wrote {output}")
    if SHOW if SHOW is not None else sys.stdout.isatty():
        show(fig)


if __name__ == "__main__":
    main()
