#!/usr/bin/env python3
"""Envelope F(E) with the discrete FC lines -- figure script generated by fcenvelope.

    python <this file> [ENVELOPE.json LINES.json]

Everything that decides how this figure looks is in this file, and the data is
read from the result JSON at run time. Recompute with different conditions and
run this script again to get the same figure for the new numbers.

This file is yours. fcenvelope never reads it back; edit anything below.
"""

from __future__ import annotations

import base64
import io
import math
import sys
import json
from pathlib import Path

import matplotlib.pyplot as plt

# --- generated header (fcenvelope) ---------------------------------------
ENVELOPE = Path(__file__).parent / "result.json"
LINES = Path(__file__).parent / "lines.json"
OUTPUT = Path(__file__).parent / "fcenvelope-overlay.png"
ENVELOPE_KIND = "fcenvelope.envelope"
LINES_KIND = "fcenvelope.fc_lines"
SCHEMA_VERSION = 2
# --- end generated header ------------------------------------------------

# 出力先。SHOW は None なら端末のときだけ、True / False で固定できる。
SAVE = True
SHOW = None
SHOW_WIDTH = 0.9     # 端末の幅に対する図の幅の割合
SHOW_DPI = 110       # 端末が画素数を返さないときの解像度。ファイルの DPI とは別
IMAGE_PREFIX = "fcenvelope-"   # 引数でほかの結果を指したときの画像名の頭

# 図の設定。ここから下はすべて手で変えてよい。
FIGSIZE = (7.0, 4.2)
DPI = 150
TITLE = None
ENVELOPE_LABEL = "envelope"
LINES_LABEL = "FC lines"
ENVELOPE_COLOR = "C0"
LINES_COLOR = "C1"
LINEWIDTH = 1.2
MAGNIFY = 1.0        # 棒だけを拡大する。倍率は凡例に出る
XLIM = None          # None ならエンベロープの E 窓。(-3000.0, 500.0) と書ける
YLIM = None
GUIDE = {"color": "0.7", "linewidth": 0.8, "zorder": 0}

# 横軸の単位。計算は常に cm^-1 で行われているので、ここは表示の掛け算だけ。
# 縦軸は密度 1/(横軸の単位) なので、曲線も棒も割って ∫F dE = 1 を保つ。
#   eV にするなら  X_UNIT, X_SCALE = "eV", 1.0 / 8065.543937
X_UNIT = "cm$^{-1}$"
X_SCALE = 1.0


def beside(path: Path | str) -> Path:
    """スクリプトの中に書いたファイル名を、このスクリプトの隣として読む。

    生成ヘッダの位置がこのファイルからの相対で解決される（ADR-0059）のに合わせる。
    2 本目を足すときに書くファイル名も同じ基準になるので、どこから起動しても同じ図が
    出る。コマンドラインの引数はシェルの都合でカレントディレクトリ基準なので、`main`
    が先に絶対パスへ直してから渡す（ADR-0067）。
    """
    path = Path(path)
    return path if path.is_absolute() else Path(__file__).parent / path


def load(path: Path | str, kind: str) -> dict:
    """結果 JSON を読む。種類と版が合わなければ読める文言で止まる。"""
    path = beside(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("kind") != kind or data.get("schema_version") != SCHEMA_VERSION:
        raise SystemExit(
            f"{path}: expected {kind} (schema {SCHEMA_VERSION}), got "
            f"{data.get('kind')!r} (schema {data.get('schema_version')!r})"
        )
    return data


def terminal_pixel_width() -> int | None:
    """端末の窓の画素幅。返さない端末もあるので、その場合は None。"""
    try:
        import fcntl
        import struct
        import termios

        packed = fcntl.ioctl(sys.stdout, termios.TIOCGWINSZ, b"\0" * 8)
    except (ImportError, OSError):
        return None
    return struct.unpack("HHHH", packed)[2] or None      # rows, cols, xpixel, ypixel


def show(fig) -> None:
    """kitty graphics protocol で端末に直接出す。別の端末なら、ここを書き替える。"""
    pixels = terminal_pixel_width()
    dpi = pixels * SHOW_WIDTH / FIGSIZE[0] if pixels else SHOW_DPI

    buffer = io.BytesIO()
    fig.savefig(buffer, format="png", dpi=dpi)
    payload = base64.standard_b64encode(buffer.getvalue())

    out, first = sys.stdout.buffer, True
    while payload:                       # 制御データは先頭のみ、以降は m= だけ
        head, payload = payload[:4096], payload[4096:]
        control = "a=T,f=100,q=2," if first else ""
        out.write(
            b"\033_G" + f"{control}m={int(bool(payload))}".encode()
            + b";" + head + b"\033\\"
        )
        first = False
    out.write(b"\n")
    out.flush()


def image_for(source: Path) -> Path:
    """図の書き出し先。引数でほかの結果を指したときは、その名前に追従する。

    既定の組み合わせなら OUTPUT で、手で書き替えたものがそのまま効く。別の
    エンベロープを指したなら、その隣に `fcenvelope-<結果の名前>-overlay.png` を置く。
    重ねた図だと名前に残すのは、同じ結果を単独で描いた図と混ざらないためである
    （ADR-0067）。
    """
    if source.resolve() == ENVELOPE.resolve():
        return OUTPUT
    return source.with_name(f"{IMAGE_PREFIX}{source.stem}-overlay.png")


def stick_heights(envelope: dict, lines: dict) -> list[float]:
    """線の重み w を F(E) と同じ縦軸へ移す。

    w に規格化した線形状の頂点値 L(0) を掛けたものが「その線が F(E) に立てる山の
    高さ」になる。ガウス型なら L(0) = 1 / (sigma * sqrt(2*pi))。こうしておくと、
    孤立した線では棒の先端が曲線の山に一致し、sigma の中に何本も密集するところでは
    曲線が棒より高くなる。線形状はエンベロープ側の条件から取る。
    """
    sigma = envelope["conditions"]["broadening"]["sigma"][0]    # [値, "cm^-1"]
    peak = 1.0 / (sigma * math.sqrt(2.0 * math.pi))
    return [line["weight"] * peak * MAGNIFY / X_SCALE for line in lines["lines"]["rows"]]


def check(envelope: dict, lines: dict) -> None:
    """同じ系・同じ温度の結果どうしでないなら、重ねる前に知らせる。"""
    if envelope["conditions"]["modes"] != lines["conditions"]["modes"]:
        print("warning: the two files were computed for different systems", file=sys.stderr)
    elif envelope["conditions"]["temperature"] != lines["conditions"]["temperature"]:
        print(
            f"warning: temperature mismatch: {envelope['conditions']['temperature']:g} K "
            f"vs {lines['conditions']['temperature']:g} K",
            file=sys.stderr,
        )

    low, high = envelope["spectrum"]["energy"][0], envelope["spectrum"]["energy"][-1]
    dropped = sum(1 for line in lines["lines"]["rows"] if not low <= line["energy"] <= high)
    if dropped:
        print(
            f"warning: {dropped} of {len(lines['lines']['rows'])} lines fall outside "
            f"the E window [{low:g}, {high:g}] cm^-1 and are not drawn",
            file=sys.stderr,
        )


def draw(ax, envelope: dict, lines: dict) -> None:
    """F(E) と離散 FC 因子を 1 枚の軸に重ねる。図の中身はここだけ。"""
    energy = [e * X_SCALE for e in envelope["spectrum"]["energy"]]
    density = [d / X_SCALE for d in envelope["spectrum"]["density"]]

    lines_label = LINES_LABEL
    if lines_label is not None and MAGNIFY != 1.0:
        lines_label = rf"{lines_label} ($\times${MAGNIFY:g})"

    ax.plot(energy, density, color=ENVELOPE_COLOR, linewidth=LINEWIDTH,
            label=ENVELOPE_LABEL, zorder=2.2)
    ax.vlines([line["energy"] * X_SCALE for line in lines["lines"]["rows"]], 0.0,
              stick_heights(envelope, lines), colors=LINES_COLOR,
              linewidth=LINEWIDTH, label=lines_label, zorder=2.1)
    ax.axvline(0.0, **GUIDE)             # E = 0 は ZPL
    ax.axhline(0.0, **GUIDE)
    ax.set_xlabel(f"$E$ / {X_UNIT}")
    ax.set_ylabel(f"$F(E)$ / 1/{X_UNIT}")
    ax.margins(x=0.0)
    ax.set_xlim(energy[0], energy[-1])


def main() -> None:
    # 引数はシェルの都合でカレントディレクトリ基準。ここで絶対パスに直しておくと、
    # 以降はスクリプトの隣を指す ENVELOPE / LINES と同じに扱える（ADR-0067）。
    if len(sys.argv) > 2:
        envelope_path, lines_path = (Path(a).absolute() for a in sys.argv[1:3])
    else:
        envelope_path, lines_path = ENVELOPE, LINES
    envelope = load(envelope_path, ENVELOPE_KIND)
    lines = load(lines_path, LINES_KIND)
    check(envelope, lines)
    output = image_for(envelope_path)

    fig, ax = plt.subplots(figsize=FIGSIZE, layout="constrained")
    draw(ax, envelope, lines)

    if TITLE is not None:
        ax.set_title(TITLE)
    if XLIM is not None:
        ax.set_xlim(*XLIM)
    if YLIM is not None:
        ax.set_ylim(*YLIM)
    if ax.get_legend_handles_labels()[1]:
        ax.legend()

    if SAVE:
        # 見た目には出ない覚え書きを PNG のテキストチャンクに入れておく。
        fig.savefig(output, dpi=DPI, metadata={
            "Software": f"fcenvelope {envelope['fcenvelope_version']}",
            "Source": f"{envelope_path.name} + {lines_path.name} "
                      f"({envelope['created_at']})",
            "Description": f"T = {envelope['conditions']['temperature']:g} K, "
                           f"sigma = {envelope['conditions']['broadening']['sigma'][0]:g} cm^-1, "
                           f"{len(lines['lines']['rows'])} lines",
        })
        print(f"wrote {output}")
    if SHOW if SHOW is not None else sys.stdout.isatty():
        show(fig)


if __name__ == "__main__":
    main()
